<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
return [
    'mats' => [
        [ 'code' => '191G', 'mat_name' => 'HYDROTHOL 191	               ', 'primary_supp' => 'WINFIELD', 'units' => ' LBS', 'cost' => '$3.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => '24DA', 'mat_name' => 'HYDROTHOL 191 GRAN	           ', 'primary_supp' => 'ALLIGARE', 'units' => ' GAL', 'cost' => '$16.11', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AGDX', 'mat_name' => '2,4-D AMINE	                   ', 'primary_supp' => 'HELENA	 ', 'units' => ' GAL', 'cost' => '$12.10', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALG7', 'mat_name' => 'AGRI-DEX	                   ', 'primary_supp' => 'ALLIGARE', 'units' => ' GAL', 'cost' => '$15.85', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALGP', 'mat_name' => 'ALLIGARE 7	                   ', 'primary_supp' => 'ALLIGARE', 'units' => ' GAL', 'cost' => '$28.88', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALGY', 'mat_name' => 'ALLIGARE PERFORMANCE WETTER	   ', 'primary_supp' => 'HELENA	 ', 'units' => ' GAL', 'cost' => '$16.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALLI', 'mat_name' => 'ALGIMYCIN	                   ', 'primary_supp' => 'ALLIGARE', 'units' => ' GAL', 'cost' => '$9.36', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALPR', 'mat_name' => 'ALLIGARE	                   ', 'primary_supp' => 'HELENA	 ', 'units' => ' GAL', 'cost' => '$12.20', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALTO', 'mat_name' => 'ALGAE PRO	                   ', 'primary_supp' => 'ADAPCO, INC', 'units' => ' LBS', 'cost' => '$28.16', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALUD', 'mat_name' => 'ALTOSID	                       ', 'primary_supp' => '888 ', 'units' => ' GAL', 'cost' => '$5.45', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALUL', 'mat_name' => 'ALUM DRUM		               ', 'primary_supp' => 'GENERAL CHEMICAL', 'units' => ' LB', 'cost' => '$0.19', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ALUM', 'mat_name' => 'ALUM (LIQUID)	               ', 'primary_supp' => 'HELENA', 'units' => ' LBS', 'cost' => '$0.58', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AMAS', 'mat_name' => 'ALUM (GRANULAR)	               ', 'primary_supp' => '888   ', 'units' => ' GAL', 'cost' => '$16.43', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AMID', 'mat_name' => 'AQUAMASTER-CHEM		           ', 'primary_supp' => 'AMTIDE LLC	', 'units' => ' OZ', 'cost' => '$5.40', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQ-K', 'mat_name' => 'AMIDE	                       ', 'primary_supp' => '888  ', 'units' => ' GAL', 'cost' => '$66.82', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQBC', 'mat_name' => 'AQUATHOL K	WINFIELD	       ', 'primary_supp' => 'ADAPCO	   ', 'units' => ' LBS', 'cost' => '$3.73', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQCL', 'mat_name' => 'AQUABAC	                       ', 'primary_supp' => '888        ', 'units' => ' QTS', 'cost' => '$10.70', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQES', 'mat_name' => 'BLUE LAGOON		               ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQMS', 'mat_name' => 'AQUATIC ECO SYSTEM-AS		   ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQNQ', 'mat_name' => 'AQUAMASTER		               ', 'primary_supp' => 'ADAPCO	   ', 'units' => ' GAL', 'cost' => '$40.66', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQPO', 'mat_name' => 'AQNIQUE MMF	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$35.31', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQPR', 'mat_name' => 'AQUAPRO	                       ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$36.27', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQSH', 'mat_name' => 'AQUAPREP	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$35.31', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQSK', 'mat_name' => 'AQUASHADE	                   ', 'primary_supp' => 'WINFIELD', 'units' => ' LB', 'cost' => '$17.70', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQSP', 'mat_name' => 'AQUATHOL SUPER K (25 LBS)	   ', 'primary_supp' => 'JOHN DEERE', 'units' => ' GAL', 'cost' => '$84.55', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'AQST', 'mat_name' => 'AQUASWEEP	                   ', 'primary_supp' => '888       ', 'units' => ' GAL', 'cost' => '$18.02', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ARGS', 'mat_name' => 'AQUASTAR		               ', 'primary_supp' => 'ALLIGARE', 'units' => ' GAL', 'cost' => '$18.24', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ARSN', 'mat_name' => 'ARGOS 9% COPPER	               ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$58.30', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ATMS', 'mat_name' => 'ARSENAL	                       ', 'primary_supp' => 'WINFIELD', 'units' => ' GAL', 'cost' => '$30.49', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BACL', 'mat_name' => 'ATMOS	                       ', 'primary_supp' => 'LD.COM	', 'units' => ' 888', 'cost' => '$2.48', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BASS', 'mat_name' => 'BARACLEAR P80	               ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$1.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BKPD', 'mat_name' => 'BASS		                   ', 'primary_supp' => '888       ', 'units' => ' QT', 'cost' => '$11.36', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BLSH', 'mat_name' => 'BLACK POND DYE		           ', 'primary_supp' => '888       ', 'units' => ' QTS', 'cost' => '$10.41', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BLUG', 'mat_name' => 'BLUE SHADOW		               ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.80', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BLYM', 'mat_name' => 'BLUEGILL		               ', 'primary_supp' => 'AQUAMASTER', 'units' => ' GAL', 'cost' => '$40.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BRCL', 'mat_name' => 'BLUEZYM	                       ', 'primary_supp' => 'AQUATIC ECO SYSTEMS ', 'units' => ' LBS', 'cost' => '$1.66', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BRDS', 'mat_name' => 'BARACLEAR	                   ', 'primary_supp' => 'BIRDX	           ', 'units' => ' GAL', 'cost' => '$80.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BREM', 'mat_name' => 'BIRD-X	                       ', 'primary_supp' => 'FLORIDA FISH FARMS', 'units' => ' EA', 'cost' => '$0.18', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BRZE', 'mat_name' => 'BREAM	                       ', 'primary_supp' => 'WINFIELD	       ', 'units' => ' GAL', 'cost' => '$24.50', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BUFR', 'mat_name' => 'BREEZE	                       ', 'primary_supp' => '888           	   ', 'units' => ' GAL', 'cost' => '$20.14', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'BULB', 'mat_name' => 'BUFFER P.S.		               ', 'primary_supp' => 'LAKE DOCTORS, INC', 'units' => ' HRL', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'C24D', 'mat_name' => 'BULB CHANGE	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$17.66', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CAPT', 'mat_name' => 'SEE 2,4-D ESTER 4#	           ', 'primary_supp' => 'SEPRO	     ', 'units' => ' GAL', 'cost' => '$28.68', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CATF', 'mat_name' => 'CAPTAIN	                       ', 'primary_supp' => '888         ', 'units' => ' EA', 'cost' => '$0.60', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CATZ', 'mat_name' => 'CATFISH		                   ', 'primary_supp' => 'AQUAFIX	     ', 'units' => ' GAL', 'cost' => '$81.26', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CITA', 'mat_name' => 'CATTZILLA	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' LBS', 'cost' => '$1.41', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CITQ', 'mat_name' => 'CITRIC ACID	                   ', 'primary_supp' => '888         ', 'units' => ' LBS', 'cost' => '$1.44', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CK	', 'mat_name' => 'CITRIQUATIC		               ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$16.79', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CKII', 'mat_name' => 'CIDE KICK	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$16.86', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CLAC', 'mat_name' => 'CIDE KICK II	               ', 'primary_supp' => 'PROSOURCE	 ', 'units' => ' GAL', 'cost' => '$13.38', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CLCT', 'mat_name' => 'CLASS ACT	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$260.40', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CLPR', 'mat_name' => 'CLEARCAST	                   ', 'primary_supp' => 'ALLIGARE	 ', 'units' => ' LB', 'cost' => '$147.66', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'COH	', 'mat_name' => 'CLIPPER	                       ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$32.64', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'COP8', 'mat_name' => 'COHERE	                       ', 'primary_supp' => 'ALLIGARE LLC', 'units' => ' GAL', 'cost' => '$9.36', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'COPG', 'mat_name' => 'COPPER 8	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' LBS', 'cost' => '$1.62', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'COPS', 'mat_name' => 'COPPER SULPHATE (GRAN)	       ', 'primary_supp' => 'HELENA	     ', 'units' => ' LB', 'cost' => '$1.51', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'COPZ', 'mat_name' => 'COPPER SULPHATE (SNOW)	       ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$17.63', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CRPL', 'mat_name' => 'COPPER Z	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$13.91', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CT-P', 'mat_name' => 'CITRUS +	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$15.52', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CT-U', 'mat_name' => 'CUTRINE-PLUS	               ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$18.64', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CT3	', 'mat_name' => 'CUTRINE ULTRA	               ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$55.64', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CTGR', 'mat_name' => 'CT301	                       ', 'primary_supp' => 'HELENA	     ', 'units' => ' LB', 'cost' => '$2.08', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'CXTR', 'mat_name' => 'CUTRINE-PLUS GRANULAR	       ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$30.58', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'DGC	', 'mat_name' => 'CAPTAIN XTR	                   ', 'primary_supp' => '888          ', 'units' => ' 888', 'cost' => '$3.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'DIQ2', 'mat_name' => 'DIPLOID GRASS CARP			   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$45.90', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'DISH', 'mat_name' => 'DIQUAT 2L	                   ', 'primary_supp' => 'HELENA	     ', 'units' => ' GAL', 'cost' => '$80.25', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'DISL', 'mat_name' => 'DIQUASH     	               ', 'primary_supp' => '888         ', 'units' => ' GAL', 'cost' => '$7.65', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'DLZ	', 'mat_name' => 'JLB OIL PLUS (DIESEL)		   ', 'primary_supp' => 'HELENA     ', 'units' => ' GAL', 'cost' => '$33.92', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'DYNA', 'mat_name' => 'DLZ	                           ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$39.59', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ECOM', 'mat_name' => 'DYNAMIC	                       ', 'primary_supp' => 'ALLIGARE ', 'units' => ' GAL', 'cost' => '$51.36', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ELM4', 'mat_name' => 'ECOMAZIPYR	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$55.12', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ELMN', 'mat_name' => 'ELEMENT 4	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$60.57', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FBAR', 'mat_name' => 'ELEMNA	                       ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$150.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FISH', 'mat_name' => 'FISH BARRIERS		           ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FLLG', 'mat_name' => 'GAMEFISH		               ', 'primary_supp' => '888        ', 'units' => ' 888', 'cost' => '$73.77', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FLLR', 'mat_name' => 'FLOC LOGS			           ', 'primary_supp' => 'RH MOORE ', 'units' => ' EA', 'cost' => '$117.70', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FLNC', 'mat_name' => 'FLOC LOG-RH MOORE	           ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FOAM', 'mat_name' => 'FLOC LOGS N/C		           ', 'primary_supp' => 'ALLIGARE ', 'units' => ' QT', 'cost' => '$4.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FTCL', 'mat_name' => 'FOAM BUSTER	                   ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FTIN', 'mat_name' => 'FOUNTAIN CLEANING		       ', 'primary_supp' => '888       ', 'units' => ' HRL', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FTRL', 'mat_name' => 'Fountain Install		       ', 'primary_supp' => '888       ', 'units' => ' HRL', 'cost' => '$80.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'FTRP', 'mat_name' => 'FOUNTAIN REMOVAL		       ', 'primary_supp' => 'THE LAKE DOCTORS, INC	  ', 'units' => ' HRL', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GAMB', 'mat_name' => 'FOUNTAIN REPAIR	               ', 'primary_supp' => '888          ', 'units' => ' EA', 'cost' => '$0.03', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GAR3', 'mat_name' => 'GAMBUSIA		               ', 'primary_supp' => '888          ', 'units' => ' GAL', 'cost' => '$86.67', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GARL', 'mat_name' => 'GARLON 3A		               ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$80.56', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GASC', 'mat_name' => 'GARLON 4	                   ', 'primary_supp' => 'SEPRO	      ', 'units' => ' OZ', 'cost' => '$15.89', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GCLN', 'mat_name' => 'GALLEON SC	                   ', 'primary_supp' => 'WINFIELD	  ', 'units' => ' GAL', 'cost' => '$26.93', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GLYP', 'mat_name' => 'GREEN CLEAN LIQUID	           ', 'primary_supp' => 'DOW	          ', 'units' => ' GAL', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GLYS', 'mat_name' => 'GLYPRO	                       ', 'primary_supp' => 'ALLIGARE	  ', 'units' => ' GAL', 'cost' => '$17.92', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GRCL', 'mat_name' => 'GLYPHOSATE 5.4	               ', 'primary_supp' => 'WINFIELD	  ', 'units' => ' LB', 'cost' => '$1.46', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GRN0', 'mat_name' => 'GREEN CLEAN	                   ', 'primary_supp' => 'HELENA	      ', 'units' => ' PTS', 'cost' => '$10.17', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GRND', 'mat_name' => 'GROUND ZERO	                   ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$20.95', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'GYPS', 'mat_name' => 'GROUNDED	                   ', 'primary_supp' => 'USA GYPSUM	  ', 'units' => ' LB', 'cost' => '$0.17', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'HABT', 'mat_name' => 'GYPSUM	                       ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$80.25', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'HARD', 'mat_name' => 'HABITAT	                       ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$33.23', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'HDRM', 'mat_name' => 'HARDBALL	                   ', 'primary_supp' => 'Lake Doctors ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'HOLD', 'mat_name' => 'Hand Removal	               ', 'primary_supp' => '888          ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'IMEP', 'mat_name' => 'HOLD		                   ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$165.85', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'IMRD', 'mat_name' => 'IMAZAPYR E-PRO2	               ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$14.31', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'IMSL', 'mat_name' => 'IMPEL RED	                   ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$55.96', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'IND	', 'mat_name' => 'IMAZAPYR 2 SL	               ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$22.68', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'INLT', 'mat_name' => 'INDUCE	                       ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$13.1', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ISLB', 'mat_name' => 'INLET	                       ', 'primary_supp' => 'AQUAFIX	      ', 'units' => ' EA', 'cost' => '$38.0', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'KAMM', 'mat_name' => 'ISLAND BUDDY	               ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$22.7', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'KMCR', 'mat_name' => 'KAMMO	                       ', 'primary_supp' => 'HELENA	      ', 'units' => ' LB', 'cost' => '$11.9', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'KOMN', 'mat_name' => 'Komeen Crystal	               ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$29.8', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'KOUT', 'mat_name' => 'KOMEEN	                       ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$49.2', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'KSCO', 'mat_name' => 'KNOCKOUT	                   ', 'primary_supp' => '888          ', 'units' => ' EA', 'cost' => '$0.00', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'KTEA', 'mat_name' => 'KASCO		                   ', 'primary_supp' => 'HELENA	      ', 'units' => ' GAL', 'cost' => '$13.57', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LAS	', 'mat_name' => 'K-TEA	                       ', 'primary_supp' => '888           ', 'units' =>  'GAL', 'cost' => '$48.15', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LENS', 'mat_name' => 'LASTIC/NUFILM		           ', 'primary_supp' => '888          ', 'units' => ' EA', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LFA	', 'mat_name' => 'FOUNTAIN LENS		           ', 'primary_supp' => '888           ', 'units' => ' EA', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LGNG', 'mat_name' => 'LAKE FOUNTAINS AND AERATION	', 'primary_supp' => 'KEY COLOUR	  ', 'units' => ' QTS', 'cost' => '$8.30	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LOBP', 'mat_name' => 'LAGUNA NEGRA	               ', 'primary_supp' => 'Lake Doctors ', 'units' => ' EA', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LOCH', 'mat_name' => 'Leftover	                   ', 'primary_supp' => 'PARKWAY	       ', 'units' => ' QTS', 'cost' => '$10.41	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'LSC	', 'mat_name' => 'LOCHNESS	                   ', 'primary_supp' => 'AQUAMASTER    ', 'units' => ' GAL', 'cost' => '$120.90	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'MAKO', 'mat_name' => 'LSC	                           ', 'primary_supp' => 'HELENA	       ', 'units' => ' QTS', 'cost' => '$19.14	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'MBGL', 'mat_name' => 'MAKO	                       ', 'primary_supp' => 'KEYCOLOUR	   ', 'units' => ' GAL', 'cost' => '$27.82	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'MKBG', 'mat_name' => 'MIDNIGHT BLUE-GALLON	       ', 'primary_supp' => 'AQUAMASTER	   ', 'units' => ' GAL', 'cost' => '$40.60	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'MNBL', 'mat_name' => 'MUCK B GONE	                   ', 'primary_supp' => 'KEY COLOUR	   ', 'units' => ' QT', 'cost' => '$6.96	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'MNFL', 'mat_name' => 'MIDNIGHT BLUE	               ', 'primary_supp' => 'APPLIED POLYMER SYSTEMS	  ', 'units' => ' EA', 'cost' => '$62.74	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'MSDK', 'mat_name' => 'MINI FLOC LOG	               ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.75	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'NAUT', 'mat_name' => 'MOSQUITO DUNKS		           ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$37.35	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'NAV	', 'mat_name' => 'NAUTIQUE	                   ', 'primary_supp' => 'WINFIELD ', 'units' => ' LB', 'cost' => '$2.77	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'NITR', 'mat_name' => 'NAVIGATE	                   ', 'primary_supp' => 'AQUAFIX     ', 'units' => ' GAL', 'cost' => '$50.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'NONE', 'mat_name' => 'NITRAFIX	                   ', 'primary_supp' => '888	       ', 'units' => ' 888', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'NTBD', 'mat_name' => 'INSPECTION ONLY-NO MATERIALS', 'primary_supp' => 'AQUAFIX     ', 'units' => ' LB', 'cost' => '$10.49	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'NUFM', 'mat_name' => 'NATURE\'S BLEND 30LB PAIL	   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$26.64	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'OPT	', 'mat_name' => 'NUFILM	                       ', 'primary_supp' => 'HELENA     ', 'units' => ' GAL', 'cost' => '$34.50	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PAK	', 'mat_name' => 'OPTIMA	                       ', 'primary_supp' => 'HELENA     ', 'units' => ' LBS', 'cost' => '$1.52	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PATH', 'mat_name' => 'PAK27	                       ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$35.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PCPK', 'mat_name' => 'PATHFINDER II	               ', 'primary_supp' => '888       ', 'units' => ' LBS', 'cost' => '$7.53	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PEND', 'mat_name' => '         WATERCURE		       ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$49.22	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PHLK', 'mat_name' => 'PENDULUM	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' LB', 'cost' => '$3.68	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PHRL', 'mat_name' => 'PHOSLOCK	                   ', 'primary_supp' => 'IN-HOUSE ', 'units' => ' HRL', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PLNT', 'mat_name' => 'PHYSICAL REMOVAL	           ', 'primary_supp' => '888       ', 'units' => ' EA', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'POL	', 'mat_name' => 'AQUATIC PLANTS		           ', 'primary_supp' => '888        ', 'units' => ' GAL', 'cost' => '$56.18	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'POST', 'mat_name' => 'POLARIS		                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$68.89	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PRCT', 'mat_name' => 'POAST	                       ', 'primary_supp' => '888       ', 'units' => ' GAL', 'cost' => '$25.14	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PROT', 'mat_name' => 'PROMATE SINKER LAKE COLORANT', 'primary_supp' => 'HELENA	   ', 'units' => ' QTS', 'cost' => '$4.21	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PRPD', 'mat_name' => 'PROMATE PROTROL	               ', 'primary_supp' => '888       ', 'units' => ' LBS', 'cost' => '$2.80	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'PZBL', 'mat_name' => 'PERFECT POND		           ', 'primary_supp' => 'AQUAFIX     ', 'units' => ' GAL', 'cost' => '$60.30	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'QST	', 'mat_name' => 'PONDZILLA BLACK	               ', 'primary_supp' => 'HELENA     ', 'units' =>  ' OZ', 'cost' => '$18.98	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RCFM', 'mat_name' => 'QUEST	                       ', 'primary_supp' => 'ANTIFOAM ', 'units' => ' GAL', 'cost' => '$0.67	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RDCM', 'mat_name' => 'RECEDE                         ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$18.55	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RDP2', 'mat_name' => 'ROUND UP CUSTOMER	           ', 'primary_supp' => '888       ', 'units' => ' GAL', 'cost' => '$44.28	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RDP3', 'mat_name' => 'ROUNDUP PRO 2.5		           ', 'primary_supp' => '888       ', 'units' => ' GAL', 'cost' => '$41.73	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'REF	', 'mat_name' => 'ROUNDUP PRO 30		           ', 'primary_supp' => 'HELENA     ', 'units' => ' LB', 'cost' => '$24.15	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'REMG', 'mat_name' => 'REFUGE	                       ', 'primary_supp' => 'HELENA	   ', 'units' => ' LB', 'cost' => '$3.28	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RENF', 'mat_name' => 'RENOVATE MAX G	               ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$3.25	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RENV', 'mat_name' => 'RENOVATE OTF	               ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$106.72	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'REW2', 'mat_name' => 'RENOVATE	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$87.47	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'REWD', 'mat_name' => 'REWARD (OHIO & SC)	           ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$84.53	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'RGD	', 'mat_name' => 'REWARD	                       ', 'primary_supp' => 'WINFIELD SOLUTIONS	      ', 'units' => ' GAL', 'cost' => '$50.29	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ROD	', 'mat_name' => 'RUGGED	                       ', 'primary_supp' => 'HELENA     ', 'units' => ' GAL', 'cost' => '$20.06	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'ROUP', 'mat_name' => 'RODEO (2.5 GAL)	               ', 'primary_supp' => 'HELENA	   ', 'units' => ' QT', 'cost' => '$50.46	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SBLU', 'mat_name' => 'ROUNDUP	                       ', 'primary_supp' => 'KEYCOLOUR ', 'units' => ' LB', 'cost' => '$8.30	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SCPN', 'mat_name' => 'SKYE BLUE	                   ', 'primary_supp' => 'WINFIELD ', 'units' => ' GAL', 'cost' => '$2.39	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SEAC', 'mat_name' => 'SCULPIN G 2,4-D AMINE GRANULAR', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$12.20	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SILE', 'mat_name' => 'SEACLEAR	                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$51.21	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SINK', 'mat_name' => 'SILENERGY	                   ', 'primary_supp' => '888       ', 'units' => ' GAL', 'cost' => '$28.20	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SKBL', 'mat_name' => 'SINKER		                   ', 'primary_supp' => 'HELENA	   ', 'units' => ' GAL', 'cost' => '$38.72	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SLC	', 'mat_name' => 'SINKERBALL	                   ', 'primary_supp' => 'AQUAMASTERS	       	      ', 'units' => ' EA', 'cost' => '$123.50	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SLTS', 'mat_name' => 'SUPER LIQUID CONCENTRATE	   ', 'primary_supp' => 'IN HOUSE	    ', 'units' => ' LBS', 'cost' => '$85.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SNRP', 'mat_name' => 'SALINITY TEST	               ', 'primary_supp' => 'SePro	        ', 'units' => ' LBS', 'cost' => '$27.95	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SODA', 'mat_name' => 'SONAR SRP	                   ', 'primary_supp' => 'HCI INDUSTRIAL ', 'units' => ' GAL', 'cost' => '$0.22	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SOGE', 'mat_name' => 'SODA ASH	                   ', 'primary_supp' => 'HELENA	        ', 'units' => ' LB', 'cost' => '$291.90	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SONE', 'mat_name' => 'SONAR GENESIS	               ', 'primary_supp' => 'HELENA	        ', 'units' => ' GAL', 'cost' => '$34.40	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SONG', 'mat_name' => 'SONAR ONE	                   ', 'primary_supp' => 'HELENA	        ', 'units' => ' LBS', 'cost' => '$2,076.24', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SONQ', 'mat_name' => 'SONAR-GALLON	               ', 'primary_supp' => 'HELENA	        ', 'units' => ' OZ', 'cost' => '$31.46	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SONR', 'mat_name' => 'SONAR Q	                       ', 'primary_supp' => 'HELENA	        ', 'units' => ' LB', 'cost' => '$16.07	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SOPR', 'mat_name' => 'SONAR AS	                   ', 'primary_supp' => 'HELENA	        ', 'units' => ' LB', 'cost' => '$37.96	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SPTN', 'mat_name' => 'SONAR PR	                   ', 'primary_supp' => 'HP PRODUCTS     ', 'units' => ' 888', 'cost' => '$19.46	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'STE	', 'mat_name' => 'SPARTAN	                       ', 'primary_supp' => '888             ', 'units' => ' LBS', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'STKR', 'mat_name' => 'ST ENZYMES			           ', 'primary_supp' => 'AQUAFIX	        ', 'units' => ' QT', 'cost' => '$7.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'STLK', 'mat_name' => 'AQUA STICKER	               ', 'primary_supp' => 'HELENA	        ', 'units' => ' OZ', 'cost' => '$90.95	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'STRY', 'mat_name' => 'STALKER	                       ', 'primary_supp' => 'HELENA	        ', 'units' => ' GAL', 'cost' => '$185.24	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SUR	', 'mat_name' => 'STINGRAY	                   ', 'primary_supp' => 'HELENA	        ', 'units' => ' GAL', 'cost' => '$22.68	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'SW	', 'mat_name' => 'SURFIX	                       ', 'primary_supp' => 'BREWER	        ', 'units' => ' EA', 'cost' => '$8.08	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TGCB', 'mat_name' => 'SUNWET	                       ', 'primary_supp' => '888            ', 'units' => ' EA', 'cost' => '$6.42	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TGCN', 'mat_name' => 'TRIPLOID GRASS CARP-CHEM BGT', 'primary_supp' => '888            ', 'units' => ' EA', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TGGA', 'mat_name' => 'TRIPLOID GRASS CARP NO CHARGE', 'primary_supp' => 'JOHN MITCHELL ', 'units' => ' GAL', 'cost' => '$11.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TPFM', 'mat_name' => 'TRIPLOID GRASS CARP-GA	       ', 'primary_supp' => '888            ', 'units' => ' GAL', 'cost' => '$85.20	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TRCE', 'mat_name' => 'TOP FILM		               ', 'primary_supp' => 'ALLIGARE	    ', 'units' => ' EA', 'cost' => '$13.53	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TRF	', 'mat_name' => 'TRACE	                       ', 'primary_supp' => '888             ', 'units' => ' GAL', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TRIB', 'mat_name' => 'FREE TRASH REMOVAL		       ', 'primary_supp' => 'WINFIELD	    ', 'units' => ' HRL', 'cost' => '$43.33	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TRRL', 'mat_name' => 'TRIBUNE	                       ', 'primary_supp' => 'IN-HOUSE	    ', 'units' => ' GAL', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TRYC', 'mat_name' => 'TRASH REMOVAL	               ', 'primary_supp' => 'HELENA	        ', 'units' => ' 1', 'cost' => '$85.60	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'TURB', 'mat_name' => 'TRYCERA	                       ', 'primary_supp' => 'WINFIELD	    ', 'units' => ' LB', 'cost' => '$42.96	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'VMDP', 'mat_name' => 'TURBULENCE	                   ', 'primary_supp' => 'AQUAFIX	        ', 'units' => ' EA', 'cost' => '$6.14	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'VS60', 'mat_name' => 'VITASTIM MD PELLETS	           ', 'primary_supp' => 'AQUAFIX	        ', 'units' => ' EA', 'cost' => '$9.25	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'VSPL', 'mat_name' => 'VITASTIM 6000	               ', 'primary_supp' => 'AQUAFIX	        ', 'units' => ' LB', 'cost' => '$13.10	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'VSS	', 'mat_name' => 'VITASTIM POLAR LM	           ', 'primary_supp' => 'AQUAFIX	     	  ', 'units' => ' GAL', 'cost' => '$11.60	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'WDST', 'mat_name' => 'VITASTIM SUMMER SLAM	       ', 'primary_supp' => 'NUFARMS AMERICAS', 'units' => ' GAL', 'cost' => '$16.21	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'WFBL', 'mat_name' => 'WEEDESTROY	                   ', 'primary_supp' => 'WINFIELD ', 'units' => ' HRL', 'cost' => '$12.31	 ', 'eff_date' => '08/05/2015' ],
        [ 'code' => 'WRTY', 'mat_name' => 'WF DILUENT BLUE RPK	           ', 'primary_supp' => '888      ', 'units' => ' GAL', 'cost' => '$0.00	 ', 'eff_date' => '08/05/2015' ],
    ]
];