<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
return [
    'account_auto' => [
        [ 'act_no' => '12345', 'act_name' => 'Lands End at Wakeville' ],
        [ 'act_no' => '54321', 'act_name' => 'Breeze Island' ],
        [ 'act_no' => '54384', 'act_name' => 'Fargone' ],
        [ 'act_no' => '54859', 'act_name' => 'Tanhurst Downs' ],
        [ 'act_no' => '12465', 'act_name' => 'The Fourth Puddle' ],
        [ 'act_no' => '12358', 'act_name' => 'There and Gone' ]
    ],
    'accounts' => [
        [
            'act_number' => '12345',
            'act_name' => 'Lands End at Wakeville',
            'act_address' => '123 West Road Ave.',
            'act_co' => 'C/O Red Frog Listings',
            'act_city' => 'orlando',
            'act_state' => 'FL',
            'act_last_serve' => 'New Account',
            'act_zip' => '32801',
            'act_district' => 'Brevard',
            'act_contact' => 'Albert Fish',
            'act_status' => 'Active',
            'act_phone' => '(321) 631-4187',
            'act_fax' => '(321) 489-3424',
            'act_mobile' => '',
            'act_email' => 'test1@this.com',
            'act_budget' => '23.00',
            'act_contact_amount' => '600',
            'act_billing_amount' => '150',
            'act_start_up_amount' => '0.00',
            'act_terms' => 'NET 10 DAYS',
            'act_cust_since' => '08/20/1998',
            'act_begin_date' => '09/01/2014',
            'act_end_date' => '08/31/2015',
            'act_address2' => 'ste 123',
            'act_status_date' => '',
            'act_type' => 'Quarterly',
            'act_type_two' => 'Sep, Dec, Mar, Jun',
            'act_office' => 'WS- Winter Springs',
            'act_title' => 'owner',
            'act_salesman' => 'FJS / Fabian J. Stern',
            'act_notes' => 'This is where a bunch of notes would go. Technician is responsible for reviewing ALL CONTENTS of field file for important information before treatment.',
            'act_site_address' => '123 W East Street',
            'act_sec_phone' => '321 123 3223',
            'act_contact_two' => 'Linda Beaer, Mgr',
            'act_corp_email' => 'www.justerRoe.com'
        ],
        [
            'act_number' => '54321',
            'act_name' => 'Breeze Island',
            'act_address' => '432 red Ave.',
            'act_city' => 'deltona',
            'act_state' => 'FL',
            'act_last_serve' => '01/01/2001',
            'act_co' => 'C/O Red Frog Listings',
            'act_zip' => '32828',
            'act_contact' => 'John Simms',
            'act_phone' => '(555) 123-1212',
            'act_fax' => '(321) 489-3424',
            'act_mobile' => '',
            'act_email' => 'test1@this.com',
            'act_budget' => '23.00',
            'act_contact_amount' => '600',
            'act_billing_amount' => '150',
            'act_start_up_amount' => '0.00',
            'act_terms' => 'NET 10 DAYS',
            'act_cust_since' => '08/20/1998',
            'act_begin_date' => '09/01/2014',
            'act_end_date' => '08/31/2015',
            'act_status' => 'Active',
            'act_address2' => 'ste 123',
            'act_status_date' => '',
            'act_type' => 'Quarterly',
            'act_type_two' => 'Sep, Dec, Mar, Jun',
            'act_office' => 'WS- Winter Springs',
            'act_title' => 'owner',
            'act_salesman' => 'FJS / Fabian J. Stern',
            'act_notes' => 'This is where a bunch of notes would go. Technician is responsible for reviewing ALL CONTENTS of field file for important information before treatment.',
            'act_site_address' => '123 W East Street',
            'act_sec_phone' => '321 123 3223',
            'act_contact_two' => 'Linda Beaer, Mgr',
            'act_corp_email' => 'www.justerRoe.com'
        ],
        [
            'act_number' => '54384',
            'act_name' => 'Fargone',
            'act_address' => '111 main St.',
            'act_city' => 'Daytona Beach',
            'act_state' => 'FL',
            'act_last_serve' => '01/01/2001',
            'act_zip' => '32121',
            'act_contact' => 'Mandy Addams',
            'act_phone' => '(453) 331-8797',
            'act_fax' => '(321) 489-3424',
            'act_mobile' => '',
            'act_email' => 'test1@this.com',
            'act_budget' => '23.00',
            'act_contact_amount' => '600',
            'act_co' => 'C/O Red Frog Listings',
            'act_billing_amount' => '150',
            'act_start_up_amount' => '0.00',
            'act_terms' => 'NET 10 DAYS',
            'act_cust_since' => '08/20/1998',
            'act_begin_date' => '09/01/2014',
            'act_end_date' => '08/31/2015',
            'act_status' => 'Active',
            'act_address2' => 'ste 123',
            'act_status_date' => '',
            'act_type' => 'Quarterly',
            'act_type_two' => 'Sep, Dec, Mar, Jun',
            'act_office' => 'WS- Winter Springs',
            'act_title' => 'owner',
            'act_salesman' => 'FJS / Fabian J. Stern',
            'act_notes' => 'This is where a bunch of notes would go. Technician is responsible for reviewing ALL CONTENTS of field file for important information before treatment.',
            'act_site_address' => '123 W East Street',
            'act_sec_phone' => '321 123 3223',
            'act_contact_two' => 'Linda Beaer, Mgr',
            'act_corp_email' => 'www.justerRoe.com'
        ],
        [
            'act_number' => '54859',
            'act_name' => 'Tanhurst Downs',
            'act_address' => '908 Brian rd.',
            'act_city' => 'miami',
            'act_state' => 'FL',
            'act_last_serve' => '01/01/2001',
            'act_zip' => '39021',
            'act_contact' => 'James Madison',
            'act_phone' => '(675) 848-3827',
            'act_fax' => '(321) 489-3424',
            'act_mobile' => '',
            'act_email' => 'test1@this.com',
            'act_co' => 'C/O Red Frog Listings',
            'act_budget' => '23.00',
            'act_contact_amount' => '600',
            'act_billing_amount' => '150',
            'act_start_up_amount' => '0.00',
            'act_terms' => 'NET 10 DAYS',
            'act_cust_since' => '08/20/1998',
            'act_begin_date' => '09/01/2014',
            'act_end_date' => '08/31/2015',
            'act_status' => 'Active',
            'act_address2' => 'ste 123',
            'act_status_date' => '',
            'act_type' => 'Quarterly',
            'act_type_two' => 'Sep, Dec, Mar, Jun',
            'act_office' => 'WS- Winter Springs',
            'act_title' => 'owner',
            'act_salesman' => 'FJS / Fabian J. Stern',
            'act_notes' => 'This is where a bunch of notes would go. Technician is responsible for reviewing ALL CONTENTS of field file for important information before treatment.',
            'act_site_address' => '123 W East Street',
            'act_sec_phone' => '321 123 3223',
            'act_contact_two' => 'Linda Beaer, Mgr',
            'act_corp_email' => 'www.justerRoe.com'
        ],
        [
            'act_number' => '12465',
            'act_name' => 'The Fourth Puddle',
            'act_address' => '909 Barrington Dr.',
            'act_city' => 'Waldorf',
            'act_state' => 'MD',
            'act_last_serve' => '01/01/2001',
            'act_zip' => '12932',
            'act_contact' => 'Thom Powers',
            'act_status' => 'Inactive',
            'act_phone' => '(854) 254-0987',
            'act_fax' => '(321) 489-3424',
            'act_mobile' => '',
            'act_email' => 'test1@this.com',
            'act_co' => 'C/O Red Frog Listings',
            'act_budget' => '23.00',
            'act_contact_amount' => '600',
            'act_billing_amount' => '150',
            'act_start_up_amount' => '0.00',
            'act_terms' => 'NET 10 DAYS',
            'act_cust_since' => '08/20/1998',
            'act_begin_date' => '09/01/2014',
            'act_end_date' => '08/31/2015',
            'act_address2' => 'ste 123',
            'act_status_date' => '',
            'act_type' => 'Quarterly',
            'act_type_two' => 'Sep, Dec, Mar, Jun',
            'act_office' => 'WS- Winter Springs',
            'act_title' => 'owner',
            'act_salesman' => 'FJS / Fabian J. Stern',
            'act_notes' => 'This is where a bunch of notes would go. Technician is responsible for reviewing ALL CONTENTS of field file for important information before treatment.',
            'act_site_address' => '123 W East Street',
            'act_sec_phone' => '321 123 3223',
            'act_contact_two' => 'Linda Beaer, Mgr',
            'act_corp_email' => 'www.justerRoe.com'
        ],
        [
            'act_number' => '12358',
            'act_name' => 'There and Gone',
            'act_address' => '843 Goddard way',
            'act_city' => 'Bushing Ward',
            'act_state' => 'OH',
            'act_last_serve' => '01/01/2001',
            'act_zip' => '04935',
            'act_contact' => 'Linda Carter',
            'act_phone' => '(418) 372-4737',
            'act_fax' => '(321) 489-3424',
            'act_mobile' => '',
            'act_email' => 'test1@this.com',
            'act_budget' => '23.00',
            'act_co' => 'C/O Red Frog Listings',
            'act_contact_amount' => '600',
            'act_billing_amount' => '150',
            'act_start_up_amount' => '0.00',
            'act_terms' => 'NET 10 DAYS',
            'act_cust_since' => '08/20/1998',
            'act_begin_date' => '09/01/2014',
            'act_end_date' => '08/31/2015',
            'act_status' => 'Active',
            'act_address2' => 'ste 123',
            'act_status_date' => '',
            'act_type' => 'Quarterly',
            'act_type_two' => 'Sep, Dec, Mar, Jun',
            'act_office' => 'WS- Winter Springs',
            'act_title' => 'owner',
            'act_salesman' => 'FJS / Fabian J. Stern',
            'act_notes' => 'This is where a bunch of notes would go. Technician is responsible for reviewing ALL CONTENTS of field file for important information before treatment.',
            'act_site_address' => '123 W East Street',
            'act_sec_phone' => '321 123 3223',
            'act_contact_two' => 'Linda Beaer, Mgr',
            'act_corp_email' => 'www.justerRoe.com'
        ]
    ],
    'field_act' => [
        [ 'code' => 'ATMS',
            'qty' => '0.01',
            'units' => 'GAL',
            'tech' => 'BRP',
            'cost' => '30.49',
            'total' => '0.300',
            'date' => '6/19/2015'
        ],
        [ 'code' => 'IND',
            'qty' => '0.01',
            'tech' => 'BRP',
            'units' => 'GAL',
            'cost' => '22.68',
            'total' => '0.23',
            'date' => '6/19/2015'
        ],
        [ 'code' => 'GLYS',
            'qty' => '0.04',
            'units' => 'GAL',
            'tech' => 'BRP',
            'cost' => '17.92',
            'total' => '0.72',
            'date' => '6/19/2015'
        ],
        [ 'code' => 'ROD',
            'qty' => '0.06',
            'units' => 'GAL',
            'cost' => '20.06',
            'tech' => 'BRP',
            'total' => '1.600',
            'date' => '3/31/2015'
        ],
        [ 'code' => 'POL',
            'qty' => '0.03',
            'units' => 'GAL',
            'tech' => 'BRP',
            'cost' => '56.18',
            'total' => '1.69',
            'date' => '3/31/2015'
        ],
        [ 'code' => 'ROD',
            'qty' => '0.08',
            'units' => 'GAL',
            'cost' => '20.06',
            'tech' => 'BRP',
            'total' => '0.16',
            'date' => '9/22/2014'
        ],
    ]
];
